name: baxter_torch
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - cython
  - flwr
  - scipy
  - matplotlib
  - pandas
  - pip
  - plotly
  - pre-commit
  - python
  - tqdm
  - wandb
  - yaml
  - pip:
      - --index-url https://download.pytorch.org/whl/cu126
      - torch<2.7
