name: baxter_torch
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - cython
  - flwr
  - keras
  - matplotlib
  - pandas
  - pip
  - plotly
  - pre-commit
  - python
  - scipy
  - tensorflow<2.17
  - tqdm
  - wandb
  - yaml
  - pip:
      - --index-url=https://download.pytorch.org/whl/cu128
      - torch
